Add: Github Actions

diff --git a/.github/workflows/github_actions.yml b/.github/workflows/github_actions.yml
--- a/.github/workflows/github_actions.yml
+++ b/.github/workflows/github_actions.yml
@@ -32,7 +32,8 @@ jobs:
           PRESETS_PATH: ${{ vars.PRESETS_PATH }}
           UTILS_PATH: ${{ vars.UTILS_PATH }}
           SUPER_SECRET_KEY: ${{ secrets.SUPER_SECRET_KEY }}
-        run: echo "Environment variables have been set."
+        run: |
+          echo "Environment variables have been set."
 
       - name: Run Unit Tests
         env:
@@ -42,6 +43,10 @@ jobs:
           UTILS_PATH: ${{ vars.UTILS_PATH }}
           SUPER_SECRET_KEY: ${{ secrets.SUPER_SECRET_KEY }}
         run: |
+          if [ ! -f $PRESETS_PATH ]; then
+            echo "presets.json not found at $PRESETS_PATH"
+            exit 1
+          fi
           bash .github/workflows/unit_tests.sh
 
       - name: Upload Test Results (Optional)
